site_name: Panlingue
site_url: https://www.pandunia.info/panlingue/por
repo_url: https://github.com/barumau/panlingue/
docs_dir: ../../por
site_dir: ../../html/por
theme:
  name: material
  language: pt
nav:
    - 'Ortografía': abc.md
    - 'Dicionarios':
        - 'Panlingue-Português': panlingue-portugali.md
        - 'Português-Panlingue': portugali-panlingue.md
        - 'Dicionario etimologico': leksaslia.md
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/viewforum.php?f=16
markdown_extensions:
  - toc:
      toc_depth: 2
