site_name: панлингвэ
site_url: https://www.pandunia.info/panlingue/rus
repo_url: https://github.com/barumau/panlingue/
docs_dir: ../../rus
site_dir: ../../html/rus
use_directory_urls: false
theme:
  name: material
  language: ru
plugins:
    - search:
        lang: ru
nav:
    - Дом: 'index.md'
    - 'Уроки': K-kurse.md
    - 'Грамматика':
        - G_baze.md
        - G-ABC.md
        - G-N.md
        - G_NUM.md
        - G-PRN.md
        - G-V.md
        - 110_jumle.md
        - G-AFX.md
    - 'Словарь':
        - 'пандуния-русский': panlingue-rusi.md
        - 'русский-пандуния': rusi-panlingue.md
        - 'этимология': leksaslia.md
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/viewforum.php?f=16
markdown_extensions:
  - toc:
      toc_depth: 2
