site_name: панлингвэ
site_url: https://www.pandunia.info/panlingue/rus
repo_url: https://github.com/barumau/panlingue/
docs_dir: ../../rus
site_dir: ../../html/rus
use_directory_urls: false
theme:
  name: material
  language: ru
plugins:
    - search:
        lang: ru
nav:
    - Дом: 'index.md'
    - 'Уроки': darse.md
    - 'Грамматика':
        - 100_bazi_kanune.md
        - G_ABC.md
        - G_N.md
        - G_NUM.md
        - G_PRO.md
        - G_V.md
        - 110_jumle.md
        - G_AFX.md
    - 'Словарь':
        - 'пандуния-русский': panlingue-rusi.md
        - 'русский-пандуния': rusi-panlingue.md
        - 'этимология': leksaslia.md
