site_name: Panlingue
site_url: https://www.pandunia.info/panlingue/epo
repo_url: https://github.com/barumau/panlingue/
docs_dir: ../../epo
site_dir: ../../html/epo
theme:
  name: material
  language: eo
nav:
    - 'Ĉefpaĝo': 'index.md'
    - 'Bazaĵoj kaj strukturo de Panlingue':
        - 'Bazaj reguloj': 100_bazi_kanun.md
        - 'Tutmonda vortaro': 101_dunia_lexe.md
        - 'Prononco': G-ABC.md
        - 'Substantivoj': G-N.md
        - 'Adjektivoj': G-ADJ.md
        - 'Adverboj': G-ADV.md
        - 'Numeraloj': G_NUM.md
        - 'Pronomoj': G-PRN.md
        - 'Verboj': G-V.md
        - 'Vortfarado': G-AFX.md
    - 'Lecionoj':
        - 'Utilaj frazoj': fraze.md
    - 'Vortaroj':
        - 'Panlingue-Esperanto': panlingue-esperanti.md
        - 'Esperanto-Panlingue': esperanti-panlingue.md
        - 'Etimologia vortaro': leksaslia.md

