site_name: Panlingue
site_url: https://www.pandunia.info/panlingue/epo
repo_url: https://github.com/barumau/panlingue/
docs_dir: ../../epo
site_dir: ../../html/epo
theme:
  name: material
  language: eo
nav:
    - 'Ĉefpaĝo': 'index.md'
    - 'Bazaĵoj kaj strukturo de Panlingue':
        - 'Bazaj reguloj': 100_bazi_kanun.md
        - 'Tutmonda vortaro': 101_dunia_lexe.md
        - 'Prononco': 102_ABC.md
        - 'Substantivoj': 104_nam-lexe.md
        - 'Adjektivoj': 105_sif-lexe.md
        - 'Adverboj': 106_mod-lexe.md
        - 'Numeraloj': 107_nume.md
        - 'Pronomoj': 108_vis-lexe.md
        - 'Verboj': 109_kar-lexe.md
        - 'Vortfarado': 111_lex-bine.md
    - 'Lecionoj':
        - 'Utilaj frazoj': fraze.md
    - 'Vortaroj':
        - 'Panlingue-Esperanto': panlingue-esperanti.md
        - 'Esperanto-Panlingue': esperanti-panlingue.md
        - 'Etimologia vortaro': leksaslia.md

