site_name: Panlingue
site_url: https://www.pandunia.info/panlingue/epo
repo_url: https://github.com/barumau/panlingue/
docs_dir: ../../epo
site_dir: ../../html/epo
use_directory_urls: false
theme:
  name: material
  language: eo
nav:
    - 'Ĉefpaĝo': 'index.md'
    - 'Bazaĵoj kaj strukturo de Panlingue':
        - 'Bazaj reguloj': G-baze.md
        - 'Tutmonda vortaro': L-lexe.md
        - 'Prononco': G-ABC.md
        - 'Substantivoj': G-N.md
        - 'Adjektivoj': G-ADJ.md
        - 'Adverboj': G-ADV.md
        - 'Numeraloj': G-NUM.md
        - 'Pronomoj': G-PRN.md
        - 'Verboj': G-V.md
        - 'Vortfarado': G-AFX.md
    - 'Lecionoj':
        - 'Utilaj frazoj': K-fraze.md
    - 'Vortaroj':
        - 'Panlingue-Esperanto': panlingue-epo.md
        - 'Esperanto-Panlingue': epo-panlingue.md
        - 'Etimologia vortaro': leksaslia.md
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/viewforum.php?f=16
    - icon: fontawesome/brands/telegram
      link: https://t.me/+xPKbG725-8E0N2E8
markdown_extensions:
  - toc:
      toc_depth: 2
