site_name: Panlingue
site_url: http://www.panlingue.info/espani
repo_url: https://github.com/barumau/panlingue/
docs_dir: ../../espani
site_dir: ../../html/espani
theme: readthedocs
nav:
    - Inicio: 'index.md'
    - 'Info':
        - 'Principios': filsofe.md
    - 'Lecciones':
        - 'Ortografía': abc.md
        - 'Frases básicas': fraze.md
        - 'Curso': darse.md
    - 'Diccionarios':
        - 'Panlingue-Español': panlingue-espani.md
        - 'Español-Panlingue': espani-panlingue.md
        - 'Diccionario etimologico': leksaslia.md

