site_name: Panlingue
site_url: http://www.panlingue.info/esperanti
repo_url: https://github.com/barumau/panlingue/
docs_dir: ../../esperanti
site_dir: ../../html/esperanti
theme: readthedocs
nav:
    - 'Ĉefpaĝo': 'index.md'
    - 'Bazaĵoj kaj strukturo de Panlingue':
        - 'Bazaj reguloj': 100_bazi_kanun.md
        - 'Tutmonda vortaro': 101_dunia_loge.md
        - 'Prononco': 102_ABC.md
        - 'Substantivoj': 104_namloge.md
        - 'Adjektivoj': 105_sifloge.md
        - 'Adverboj': 106_modologe.md
        - 'Numeraloj': 107_numloge.md
        - 'Pronomoj': 108_visloge.md
        - 'Verboj': 109_karloge.md
        - 'Vortfarado': 111_logobine.md
    - 'Lecionoj':
        - 'Utilaj frazoj': fraze.md
    - 'Vortaroj':
        - 'Panlingue-Esperanto': panlingue-esperanti.md
        - 'Esperanto-Panlingue': esperanti-panlingue.md
        - 'Etimologia vortaro': leksaslia.md

