site_name: 泛世界语
site_url: http://www.panlingue.info/cini
repo_url: https://github.com/barumau/panlingue/
docs_dir: ../../cini
site_dir: ../../html/cini
theme: cerulean
nav:
    - Home: 'index.md'
    - '字母表': abc.md
    - '短语集': fraze.md
    - '词典': panlingue-cini.md
    - '语源': leksaslia.md

