site_name: 泛话
site_url: https://www.pandunia.info/panlingue/cmn
repo_url: https://github.com/barumau/panlingue/
docs_dir: ../../cmn
site_dir: ../../html/cmn
theme: material
nav:
    - Home: 'index.md'
    - '字母表': G-ABC.md
    - '短语集': fraze.md
    - '词典': panlingue-cini.md
    - '语源': leksaslia.md
