site_name: 泛话
site_url: https://www.pandunia.info/panlingue/cmn
repo_url: https://github.com/barumau/panlingue/
docs_dir: ../../cmn
site_dir: ../../html/cmn
use_directory_urls: false
theme:
  name: material
  palette:
    primary: green
nav:
    - Home: 'index.md'
    - '字母表': G-ABC.md
    - '短语集': fraze.md
    - '词典': panlingue-cmn.md
    - '语源': leksaslia.md
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/viewforum.php?f=16
    - icon: fontawesome/brands/telegram
      link: https://t.me/+xPKbG725-8E0N2E8
