site_name: Panlingue
site_url: http://www.panlingue.info/polski
repo_url: https://github.com/barumau/panlingue/
docs_dir: ../../polski
site_dir: ../../html/polski
theme:
  name: cerulean
  language: pl
nav:
    - Główna: 'index.md'
    - 'Info':
        - 'Wprowadzenie': dunia_baxe.md
        - 'Założenia': filsofe.md
    - 'Nauka':
        - 'Dźwięki i litery': abc.md
        - 'Rozmówki': fraze.md
        - 'Kurs': darse.md
    - 'Słownik':
        - 'Panlingue-polski': panlingue-polski.md
        - 'Polski-panlingue': polski-panlingue.md
        - 'Etymologia': leksaslia.md
        - 'Wyszukaj': tiddly.html
    - 'Gramatyka': kanun.md

