site_name: Panlingue
site_url: http://www.panlingue.info/espani
repo_url: https://github.com/barumau/panlingue/
docs_dir: ../../portugali
site_dir: ../../html/portugali
theme: readthedocs
nav:
    - Inicio: 'index.md'
    - 'Ortografía': abc.md
    - 'Dicionarios':
        - 'Panlingue-Português': panlingue-portugali.md
        - 'Português-Panlingue': portugali-panlingue.md
        - 'Dicionario etimologico': leksaslia.md

