site_name: Panlingue
site_url: http://www.panlingue.info/engli
repo_url: https://github.com/barumau/panlingue/
site_author: Risto Kupsala
docs_dir: ../../engli
site_dir: ../../html/engli
theme: readthedocs
nav:
    - Home: 'index.md'
    - 'Info':
        - 'Introduction': dunia_baxe.md
        - 'Principles': filsof.md
    - 'Grammar and Rules':
        - 'The basic rules': 100_bazi_kanune.md
        - 'World words': 101_duni_lekse.md
        - 'Spelling and pronunciation': 102_ABC.md
        - 'Word class markers': 103_logotipe.md
        - 'Nouns': 104_namloge.md
        - 'Adjectives': 105_sifloge.md
        - 'Adverbs': 106_modologe.md
        - 'Numerals': 107_nume.md
        - 'Pronouns': 108_visloge.md
        - 'Verbs': 109_karloge.md
        - 'Sentences': 110_jumle.md
        - 'Word building': 111_logobine.md
    - 'Lessons':
        - 'Basic Phrases': fraze.md
        - 'Course': darse.md
    - 'Words':
        - 'Panlingue-English': panlingue-engli.md
        - 'English-Panlingue': engli-panlingue.md
        - 'Origins of words': leksaslia.md
        - 'Search': tiddly.html
    - 'Appendix':
        - History: 401_historia.md
        - 'Questions & Answers': eske_i_jawabe.md
        - 'Translate this site': tarja_netoloke.md

