site_name: Panlingue
site_url: https://www.pandunia.info/panlingue/eng
repo_url: https://github.com/barumau/panlingue/
site_author: Risto Kupsala
docs_dir: ../../eng
site_dir: ../../html/eng
use_directory_urls: false
theme:
  name: material
  font:
    code: Ubuntu mono
extra_css:
  - stile.css
nav:
    - 'Info':
        - 'Introduction': dunia_baxe.md
        - 'Principles': filsof.md
    - 'Grammar and Rules':
        - 'The basic rules': 100_bazi_kanune.md
        - 'World words': 101_dunia_lexe.md
        - 'Spelling and pronunciation': G-ABC.md
        - 'Word class markers': G-PoS.md
        - 'Nouns': G-N.md
        - 'Adjectives': G-ADJ.md
        - 'Adverbs': G-ADV.md
        - 'Numerals': G_NUM.md
        - 'Pronouns': G-PRN.md
        - 'Verbs': G-V.md
        - 'Sentences': 110_jumle.md
        - 'Word building': G-AFX.md
    - 'Lessons':
        - 'Basic Phrases': fraze.md
        - 'Course': darse.md
    - 'Words':
        - 'Panlingue-English': panlingue-engli.md
        - 'English-Panlingue': engli-panlingue.md
        - 'Origins of words': leksaslia.md
        - 'Search': tiddly.html
    - 'Appendix':
        - History: 401_historia.md
        - 'Questions & Answers': eske_i_jawabe.md
        - 'Translate this site': tarja_netoloke.md

