site_name: Panlingue
site_url: https://www.pandunia.info/panlingue/eng
repo_url: https://github.com/barumau/panlingue/
site_author: Risto Kupsala
docs_dir: ../../eng
site_dir: ../../html/eng
use_directory_urls: false
theme:
  name: material
  font:
    code: Ubuntu mono
extra_css:
  - stile.css
nav:
    - 'Info':
        - 'Introduction': I-idea.md
        - 'Principles': filsof.md
    - 'Grammar and Rules':
        - 'The basic rules': G-baze.md
        - 'World words': L-lexe.md
        - 'Spelling and pronunciation': G-ABC.md
        - 'Word class markers': G-PoS.md
        - 'Nouns': G-N.md
        - 'Adjectives': G-ADJ.md
        - 'Adverbs': G-ADV.md
        - 'Numerals': G-NUM.md
        - 'Pronouns': G-PRN.md
        - 'Verbs': G-V.md
        - 'Prepositions': G-PP.md
        - 'Sentences': G-jumle.md
        - 'Word building': G-AFX.md
    - 'Lessons':
        - 'Basic Phrases': K-fraze.md
        - 'Course': K-kurse.md
    - 'Words':
        - 'Panlingue-English': panlingue-eng.md
        - 'English-Panlingue': eng-panlingue.md
        - 'Origins of words': leksaslia.md
        - 'Search': tiddly.html
    - 'Appendix':
        - History: I-historia.md
        - 'Questions & Answers': FAQ.md
        - 'Translate this site': tarja_netoloke.md
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/viewforum.php?f=16
    - icon: fontawesome/brands/telegram
      link: https://t.me/+xPKbG725-8E0N2E8
markdown_extensions:
  - toc:
      toc_depth: 2

