site_name: Panlingue
site_url: http://www.panlingue.info/suomi
repo_url: https://github.com/barumau/panlingue/
site_author: Risto Kupsala
docs_dir: ../../suomi
site_dir: ../../html/suomi
theme: readthedocs
plugins:
    - search:
        lang: fi
nav:
    - Kotisivu: 'index.md'
    - 'Tietoa':
        - 'Maailman yhteyskieli': dunia_baxe.md
        - 'Kysymyksiä & vastauksia': eske_i_jawabe.md
    - 'Panlinguen perusteet ja rakenne':
        - 'Perussäännöt': 100_bazi_kanune.md
        - 'Yleismaailmallinen sanasto': 101_dunia_loge.md
        - 'Ääntäminen': 102_ABC.md
        - 'Substantiivit': 104_namloge.md
        - 'Adjektiivit': 105_sifloge.md
        - 'Adverbit': 106_modologe.md
        - 'Numeraalit': 107_numloge.md
        - 'Pronominit': 108_visloge.md
        - 'Verbit': 109_karloge.md
        - 'Lauserakenteita': 110_jumle.md
    - 'Oppitunteja':
        - 'Lauseita': fraze.md
        - 'Kurssi': darse.md
    - 'Sanasto':
        - 'Panlingue-suomi': panlingue-suomi.md
        - 'Suomi-panlingue': suomi-panlingue.md
        - 'Alkuperäsanasto': leksaslia.md

