site_name: Panlingue
site_url: https://www.pandunia.info/panlingue/fra
repo_url: https://github.com/barumau/panlingue/
docs_dir: ../../fra
site_dir: ../../html/fra
theme:
  name: material
  language: fr
extra_css:
  - stile.css
plugins:
    - search:
        lang: fr
nav:
    - Accueil: 'index.md'
    - 'Info':
        - 'Présentation': I-idea.md
        - 'Principes de fonctionnement': filsofe.md
        - 'Questions et réponses': FAQ.md
        - 'Traduire ce site': tarja_netoloke.md
    - 'Grammaire':
        - G-baze.md
        - L-lexe.md
        - G-ABC.md
        - G-N.md
        - G-ADJ.md
        - G-ADV.md
        - G_NUM.md
        - G-PRN.md
        - G-V.md
        - 110_jumle.md
        - G-AFX.md
    - 'Leçons':
        - 'Phrases courantes': fraze.md
        - 'Leçons': K-kurse.md
    - 'Vocabulaire':
        - 'Panlingue → français': panlingue-fransi.md
        - 'Français → panlingue': fransi-panlingue.md
        - 'Etymologie': leksaslia.md
        - 'Recherche': tiddly.html
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/viewforum.php?f=16
markdown_extensions:
  - toc:
      toc_depth: 2
