site_name: Panlingue
site_url: https://www.pandunia.info/panlingue/fra
repo_url: https://github.com/barumau/panlingue/
docs_dir: ../../fra
site_dir: ../../html/fra
theme:
  name: material
  language: fr
extra_css:
  - stile.css
plugins:
    - search:
        lang: fr
nav:
    - Accueil: 'index.md'
    - 'Info':
        - 'Présentation': dunia_baxe.md
        - 'Principes de fonctionnement': filsofe.md
        - 'Questions et réponses': 402_sual_e_javabe.md
        - 'Traduire ce site': tarja_netoloke.md
    - 'Grammaire':
        - 100_bazi_kanune.md
        - 101_dunia_lexe.md
        - G-ABC.md
        - G-N.md
        - G-ADJ.md
        - G-ADV.md
        - G_NUM.md
        - G-PRN.md
        - G-V.md
        - 110_jumle.md
        - G-AFX.md
    - 'Leçons':
        - 'Phrases courantes': fraze.md
        - 'Leçons': darse.md
    - 'Vocabulaire':
        - 'Panlingue → français': panlingue-fransi.md
        - 'Français → panlingue': fransi-panlingue.md
        - 'Etymologie': leksaslia.md
        - 'Recherche': tiddly.html
